apiVersion: v1
kind: PersistentVolume
metadata: 
  name: weshopify-db-pv
  lables: 
    name: weshopify-db-pv
spec: 
  capacity:
    storage: 4Gi
  accessModes: 
    - ReadwriteOnce
  persistentvolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /opt/mysql